---
openapi: 3.0.1
components:
  securitySchemes:
    ApiKeyAuth: # arbitrary name for the security scheme
      type: apiKey
      in: header # can be "header", "query" or "cookie"
      name: Authorization
security:
  - ApiKeyAuth: []
info:
  title: API V1
  version: v1
paths:
  '/auth/login':
    post:
      summary: Authorization
      tags:
        - Login
      responses:
        '200':
          description: Login authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  exp:
                    type: string
                  username:
                    type: string
                  userId:
                    type: string
                  accessLevel:
                    type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string

  '/memories':
    get:
      summary: Return all Memories
      tags:
        - Memories
      responses:
        '200':
          description: token generated
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    key:
                      type: string
                    value:
                      type: string
                    visibility:
                      type: boolean
    post:
      summary: Create Memory
      tags:
        - Memories
      responses:
        '201':
          description: token generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_id:
                    type: integer
                  key:
                    type: string
                  value:
                    type: string
                  visibility:
                    type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                value:
                  type: string
                visibility:
                  type: boolean
  '/memories/{memoryId}':
    put:
      summary: Update Memory
      tags:
        - Memories
      parameters:
        - in: path
          name: memoryId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: token generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_id:
                    type: integer
                  key:
                    type: string
                  value:
                    type: string
                  visibility:
                    type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                value:
                  type: string
                visibility:
                  type: boolean
    delete:
      summary: Delete Memory
      tags:
        - Memories
      parameters:
        - in: path
          name: memoryId
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: token generated
servers:
  - url: https://memory-app-back.herokuapp.com
  - url: http://localhost:3000
